# see https://github.com/golangci/golangci-lint#configuration

run:
  timeout: 3m
  tests: false
  skip-dirs:
    - gen

linters:
  enable:
    - goimports
    - misspell
    - gofumpt
    - gofmt
    - gocritic
