# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "vendor|internal/proto"
repos:
  # common
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  # go
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: golangci-lint
        args: [--fix]
